import pandas as pd
from soccer_one_twos_extractor.constants.fields import F


# ──────────────────────────────────────────────────────────────────────────────
# Event types mapping
# ──────────────────────────────────────────────────────────────────────────────
EVENT_TYPE_MAP = {
    1: "Pass",
    2: "Offside Pass",
    3: "Take On",
    4: "Foul",
    5: "Out",
    6: "Corner Awarded",
    7: "Tackle",
    8: "Interception",
    9: "Turnover",
    10: "Save",
    11: "Claim",
    12: "Clearance",
    13: "Miss",
    14: "Post",
    15: "Attempt Saved",
    16: "Goal",
    17: "Card",
    18: "Player off",
    19: "Player on",
    20: "Player retired",
    21: "Player returns",
    22: "Player becomes goalkeeper",
    23: "Goalkeeper becomes player",
    24: "Condition change",
    25: "Official change",
    27: "Start delay",
    28: "End delay",
    30: "End",
    31: "Picked an orange",
    32: "Start",
    34: "Team set up",
    35: "Player changed position",
    36: "Player changed Jersey number",
    37: "Collection End",
    38: "Temp_Goal",
    39: "Temp_Attempt",
    40: "Formation change",
    41: "Punch",
    42: "Good Skill",
    43: "Deleted event",
    44: "Aerial",
    45: "Challenge",
    47: "Rescinded card",
    49: "Ball recovery",
    50: "Dispossessed",
    51: "Error",
    52: "Keeper pick-up",
    53: "Cross not claimed",
    54: "Smother",
    55: "Offside provoked",
    56: "Shield ball opp",
    57: "Foul throw-in",
    58: "Penalty faced",
    59: "Keeper Sweeper",
    60: "Chance missed",
    61: "Ball touch",
    63: "Temp_Save",
    64: "Resume",
    65: "Contentious referee decision",
    67: "50/50",
    68: "Referee drop ball",
    69: "Failed To Block",
    72: "Caught offside",
    73: "Other Ball Contact",
    74: "Blocked pass",
}

# 2. Qualifier Mapping (all keys as str for consistency)
QUALIFIER_MAP = {
    1: "Long ball",
    2: "Cross",
    3: "Head pass",
    4: "Through ball",
    5: "Free kick taken",
    6: "Corner taken",
    7: "Players caught offside",
    8: "Goal disallowed",
    9: "Penalty",
    10: "Hand",
    11: "6-seconds violation",
    12: "Dangerous play",
    13: "Foul",
    14: "Last line",
    15: "Head",
    16: "Small box-centre",
    17: "Box-centre",
    18: "Out of box-centre",
    19: "35+ centre",
    20: "Right footed",
    21: "Other body part",
    22: "Regular play",
    23: "Fast break",
    24: "Set piece",
    25: "From corner",
    26: "Free kick",
    28: "Own goal",
    29: "Assisted",
    30: "Involved",
    31: "Yellow Card",
    32: "Second yellow",
    33: "Red card",
    34: "Referee abuse",
    35: "Argument",
    36: "Fight",
    37: "Time wasting",
    38: "Excessive celebration",
    39: "Crowd interaction",
    40: "Other reason",
    41: "Injury",
    42: "Tactical",
    44: "Player position",
    49: "Attendance figure",
    50: "Official position",
    51: "Official ID",
    53: "Injured player id",
    54: "End cause",
    55: "Related event ID",
    56: "Zone",
    57: "End type",
    59: "Jersey number",
    60: "Small box-right",
    61: "Small box-left",
    62: "Box-deep right",
    63: "Box-right",
    64: "Box-left",
    65: "Box-deep left",
    66: "Out of box-deep right",
    67: "Out of box-right",
    68: "Out of box-left",
    69: "Out of box-deep left",
    70: "35+ right",
    71: "35+ left",
    72: "Left footed",
    73: "Left",
    74: "High",
    75: "Right",
    76: "Low left",
    77: "High left",
    78: "Low centre",
    79: "High centre",
    80: "Low right",
    81: "High right",
    82: "Blocked",
    83: "Close left",
    84: "Close right",
    85: "Close high",
    86: "Close left and high",
    87: "Close right and high",
    88: "High claim",
    89: "1 on 1",
    90: "Deflected save",
    91: "Dive and deflect",
    92: "Catch",
    93: "Dive and catch",
    94: "Def block",
    95: "Back pass",
    96: "Corner situation",
    97: "Direct free",
    100: "Six yard blocked",
    101: "Saved off line",
    102: "Goal mouth y co-ordinate",
    103: "Goal mouth z co-ordinate",
    106: "Attacking Pass",
    107: "Throw-in",
    108: "Volley",
    109: "Overhead",
    110: "Half Volley",
    111: "Diving Header",
    112: "Scramble",
    113: "Strong",
    114: "Weak",
    115: "Rising",
    116: "Dipping",
    117: "Lob",
    118: "One Bounce",
    119: "Few Bounces",
    120: "Swerve Left",
    121: "Swerve Right",
    122: "Swerve Moving",
    123: "Keeper Throw",
    124: "Goal Kick",
    127: "Direction of play",
    128: "Punch",
    130: "Team formation",
    131: "Team player formation",
    132: "Dive",
    133: "Deflection",
    134: "Far Wide Left",
    135: "Far Wide Right",
    136: "Keeper Touched",
    137: "Keeper Saved",
    138: "Hit Woodwork",
    139: "Own Player",
    140: "Pass End X",
    141: "Pass End Y",
    144: "Deleted event type",
    145: "Formation slot",
    146: "Blocked x co-ordinate",
    147: "Blocked y co-ordinate",
    153: "Not past goal line",
    154: "Intentional assist",
    155: "Chipped",
    156: "Lay-off",
    157: "Launch",
    158: "Persistent infringement",
    159: "Foul and abusive language",
    160: "Throw-in set piece",
    161: "Encroachment",
    162: "Leaving field",
    163: "Entering field",
    164: "Spitting",
    165: "Professional foul",
    166: "Handling on the line",
    167: "Out of play",
    168: "Flick-on",
    169: "Leading to attempt",
    170: "Leading to goal",
    171: "Rescinded card",
    172: "No impact on timing",
    173: "Parried safe",
    174: "Parried danger",
    175: "Fingertip",
    176: "Caught",
    177: "Collected",
    178: "Standing",
    179: "Diving",
    180: "Stooping",
    181: "Reaching",
    182: "Hands",
    183: "Feet",
    184: "Dissent",
    185: "Blocked cross",
    186: "Scored",
    187: "Saved",
    188: "Missed",
    189: "Player not visible",
    190: "From shot off target",
    191: "Off the ball foul",
    192: "Block by hand",
    194: "Captain",
    195: "Pull Back",
    196: "Switch of play",
    197: "Team kit",
    198: "GK hoof",
    199: "Gk kick from hands",
    200: "Referee stop",
    201: "Referee delay",
    202: "Weather problem",
    203: "Crowd trouble",
    204: "Fire",
    205: "Object thrown on pitch",
    206: "Spectator on pitch",
    207: "Awaiting officials decision",
    208: "Referee Injury",
    209: "Game end",
    210: "Assist",
    211: "Overrun",
    212: "Length",
    213: "Angle",
    214: "Big Chance",
    215: "Individual Play",
    216: "2nd related event ID",
    217: "2nd assisted",
    218: "2nd assist",
    219: "Players on both posts",
    220: "Player on near post",
    221: "Player on far post",
    222: "No players on posts",
    223: "In-swinger",
    224: "Out-swinger",
    225: "Straight",
    226: "Suspended",
    227: "Resume",
    228: "Own shot blocked",
    229: "Post-match complete",
    230: "GK X Coordinate",
    231: "GK Y Coordinate",
    232: "Unchallenged",
}

COLUMN_RENAMES = {"involved": F.PLAYER_ID}

EVENT_TYPE_MAPPING_DF = pd.DataFrame(
    [{F.TYPE_ID: str(k), F.EVENT_NAME: v} for k, v in EVENT_TYPE_MAP.items()]
)

QUALIFIER_ID_TO_NAME = {str(k): v for k, v in QUALIFIER_MAP.items()}

QUALIFIER_NAME_TO_ID = {v: k for k, v in QUALIFIER_MAP.items()}
